.PHONY: clean All

All:
	@echo "----------Building project:[ CarRental - Debug ]----------"
	@cd "CarRental" && "$(MAKE)" -f  "CarRental.mk"
clean:
	@echo "----------Cleaning project:[ CarRental - Debug ]----------"
	@cd "CarRental" && "$(MAKE)" -f  "CarRental.mk" clean
